### PR TITLE
Added patch option to Makefile

### PR DESCRIPTION
**Pull request by thecozies**

### CODE REVIEW

**Comment by thecozies** [comment]
@CrashOveride95 thoughts?

**Comment by CrashOveride95** [comment]
I am currently on vacation so I won't have time to review PRs much for a few days, sorry

**Comment by Reonu** [comment]
@CrashOveride95  A vacation... course? Have you remembered how to jump yet?

**Comment by CrashOveride95** [comment]
boooo

**Comment by thecozies** [comment]
@CrashOveride95 well I think I may have jumped the gun on the whole submodule thing. When cloning a repo with submodules you have to initialize them and that could get annoying or confusing to some. What if I added submodule initialization to the Makefile when making tools?

**Comment by CrashOveride95** [comment]
Flips's codebase is huge and I hate doing submodules

I'll probably try to make it more portable so it can be a new tool but for now I'm closing this

**Pull request closed without merging**
